apiVersion: v1
kind: Pod

metadata:
  name: spring-pod

spec:
  containers:
    - name: spring-container
      image: spring-server
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent


# 이미지 풀 정책 (Image Pull Policy)
# Always 로컬 이미지 가져오지 않고 레지스트리(DockerHup이나 외부의 이미지)를 가져오게됨
# IfNotPresent 로컬이미지를 가져오고 없다면 레지스트리에서 가져옴
# Never 로컬에서만 이미지 가져옴

# image에 latest거나 명시하지 않으면 Always로 설정
# latest가 아니면 IfNotPresent로 설정



